pipeline {
    agent any

    stages {
         stage('Pull') {
            steps {
                git branch: 'main', credentialsId: 'b9f7d06b-5685-42ba-8bdd-8e5cabb980f2', url: 'https://gitee.com/fan-bin/shop_grpc.git'
            }
        }

        stage('Build') {
            steps {
                sh 'echo "[build.sh]" && cd shop_api && chmod +x ${web_name}/build.sh && /bin/bash ${web_name}/build.sh'
            }
        }

        stage('Start') {
            steps {
                sshPublisher(publishers: [sshPublisherDesc(configName: '192.168.139.130', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'mkdir -p /data/${web_name}/shop_api/tmp/log/${web_name}/ && cd /data/${web_name}/shop_api/ && chmod +x ${web_name}/start.sh && /bin/bash ${web_name}/start.sh', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '${web_name}/', remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'shop_api/${web_name}/config-debug.yaml,shop_api/${web_name}/config-pro.yaml,shop_api/${web_name}_main,shop_api/${web_name}/start.sh')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }

    }
}
